### ISSUE TITLE
How do you install this?

### ISSUE THREAD

**Issue by djasnowski** [adamwathan/laravel-preset#1]
I'm not extremely new to Laravel (read: I just finish Jeffrey's 100-episode forum series) but I have no idea how to install this. Maybe I'm missing something but I don't see installation instructions...

And before you shout at me, yes I have tried googling and nothing came up.

Sorry if this isn't the right place.

**Comment by n1dre** [comment]
Because this repo isn't on packagist you can't `composer require` it. 
You'll have to add the repo in `composer.json`:
```
"require-dev": {
    "adamwathan/laravel-preset" : "dev-master"
},
"repositories": [
    {
        "type": "vcs",
        "url": "https://github.com/adamwathan/laravel-preset"
    }
]
```
Run `composer update` and then install the preset with `php artisan preset nothingworks` 🤘

**Comment by djasnowski** [comment]
Thank you! I very much appreciate it. 👋

**Comment by adamwathan** [comment]
Yep @nikje94 nailed it! I should obviously add this to the README 🤦‍♂️

**Comment by Helfull** [comment]
hey, is there any reason why you dont put it on packagist?

**Comment by adamwathan** [comment]
I was holding off in case I could come up with a cooler name 😄

**Comment by emjayess** [comment]
> I was holding off in case I could come up with a cooler name 😄

Maybe like `nothingworks/breakwind-preset` 😛 

Can the `php artisan preset nothingworks` be added to the "scripts" composer block?

**Comment by nuno360** [comment]
I'm getting this error:

```
[InvalidArgumentException]                                                                                                                                            
Could not find a version of package adamwathan/laravel-preset matching your minimum-stability (stable).
Require it with an explicit version constraint allowing its desired stability
```

```
{
    "name": "adamwathan/laravel-preset",
    "description": "Adam Wathan's Laravel Frontend Preset",
    "keywords": ["laravel", "preset"],
    "license": "MIT",
    "require": {
        "laravel/framework": "^5.7"
    },
    "repositories": [
	    {
	        "type": "vcs",
	        "url": "https://github.com/adamwathan/laravel-preset"
	    }
	],
    "autoload": {
        "psr-4": {
            "NothingWorks\\LaravelPreset\\": "src/"
        }
    },
    "extra": {
        "laravel": {
            "providers": [
                "NothingWorks\\LaravelPreset\\PresetServiceProvider"
            ]
        }
    }
}
```

Composer version 1.8.6 2019-06-11 15:03:05
