### ISSUE TITLE
Initialised tailwind but not compiling custom colors

### ISSUE THREAD

**Issue by roarkmccolgan** [adamwathan/laravel-preset#4]
Hi Guys,

I've initialised tailwind using tailwind init and the config is generated in my root, but my custom colors are not being compiled, am I missing a step?

Thanks in advance

**Comment by adamwathan** [comment]
Make sure you edit your `webpack.mix.js` file to include the path to your config file. By default, this preset doesn't pass in any path at all and just uses Tailwind's defaults.

**Comment by roarkmccolgan** [comment]
Thank you Adam,
Apologies for what might be a stupid question but where do I include the path exactly?
```
mix.js('resources/assets/js/app.js', 'public/js').version()
  .postCss('resources/assets/css/app.css', 'public/css')
  .options({
    postCss: [
      require('postcss-import')(),
      require('tailwindcss')(),
      require('postcss-cssnext')({
        // Mix adds autoprefixer already, don't need to run it twice
        features: { autoprefixer: false }
      }),
    ]
  })
  .purgeCss()
```

Thanks!

**Comment by adamwathan** [comment]
Haha all good, should've been more clear, here:

```diff
    // ... 
-   require('tailwindcss')(),
+   require('tailwindcss')('./tailwind.js'),
    // ...
```

**Comment by roarkmccolgan** [comment]
Thank you sir!
*Queues up laracast Laravel Mix lessons*
